
import
  os,
  re,
  bitops,
  strutils,
  strformat,
  parseopt


proc cvt_file(filename: string, out_h_str: var string, out_c_str: var string, out_c_str_g: var string)
proc bytestohex_color(byte1, byte2: string): string
proc color_code_256to16(byte: string): int


proc main() =
  var
    out_c: string
    out_h: string
    pgm_dir: string
    out_c_buf: string
    out_c_buf_g: string # globals
    out_h_buf: string

  for kind, key, val in getopt():
    case kind
      of cmdShortOption, cmdLongOption, cmdArgument:
        case key
          of "h": out_h = val
          of "c": out_c = val
          of "p": pgm_dir = val
      of cmdEnd: assert(false)

  if out_h.len == 0 or out_c.len == 0:
    echo "Usage: pgm2c -h header.h -c source.c -p path/to/pgm_files"
    quit QuitFailure

  out_h_buf = """/* C header auto-generated by pgm2c, do not edit! */

#include "omgui.h"

void Bitmaps_Init(void);

"""

  for path in walkFiles(&"{pgm_dir}/*.pgm"):
    path.cvt_file(out_h_buf, out_c_buf, out_c_buf_g)

  out_c_buf = """/* C source auto-generated by pgm2c, do not edit! */

#include "omgui.h"

""" & out_c_buf_g & """

void Bitmaps_Init(void)
{
""" & out_c_buf & "}\n"

  out_h.writeFile(out_h_buf)
  out_c.writeFile(out_c_buf)


proc cvt_file(filename: string, out_h_str: var string, out_c_str: var string, out_c_str_g: var string) =
  let name = splitFile(filename)[1]

  var
    fd_in = filename.open()
    line: string
    outcbuf: string

    im_width: uint
    im_height: uint
    im_colors: uint

    color_mark: bool
    data_sem: bool
    bytes_in_row_cnt: uint = 0
    nbytes = 0
    is_byte1 = true
    byte1, byte2: string

  while fd_in.readLine(line):
    if line[0] == '#' or line == "P2": # header
      continue

    elif line =~ re"^(\d+)\s+(\d+)$": # width height
      (im_width, im_height) = (matches[0].parseUInt, matches[1].parseUInt)
      outcbuf = &"  uint32_t bitmap_{name}_data[{(im_width*im_height).div(2)}] = " & "{\n"
      color_mark = true

    elif color_mark: # colors
      im_colors = line.parseUInt
      color_mark = false

    elif is_byte1:
        byte1 = line
        is_byte1 = false
        continue
    else: # byte2
      byte2 = line
      let color8bit = bytestohex_color(byte1, byte2)

      var not_1st_ln = "," & color8bit

      if bytes_in_row_cnt == im_width.div(2):
        not_1st_ln = ",\n" & color8bit
        bytes_in_row_cnt = 0

      outcbuf &= (if data_sem: not_1st_ln else: color8bit)

      bytes_in_row_cnt.inc
      nbytes.inc

      data_sem = true
      is_byte1 = true

  fd_in.close()

  echo &"{filename.extractFilename()}: {nbytes} color bytes created"

  outcbuf = &"  bitmap_{name}.Width = {im_width};\n" &
    &"  bitmap_{name}.Height = {im_height};\n" &
    &"  bitmap_{name}.IsAlpha = False;\n" &
    &"  bitmap_{name}.ColorsNumOf = 16;\n" &
    outcbuf & "\n};\n" &
    &"  bitmap_{name}.RawData = bitmap_{name}_data;\n\n"

  out_h_str &= &"extern omBitmapT bitmap_{name};\n"
  out_c_str &= outcbuf
  out_c_str_g &= &"omBitmapT bitmap_{name};\n"


proc bytestohex_color(byte1, byte2: string): string =
  let
    ibyte1 = color_code_256to16 byte1
    ibyte2 = color_code_256to16 byte2
    # merge two 4-bit colors to 1 byte (2222 1111)
    icolor2x = ibyte2.shl(4).bitor(ibyte1)

  result = (if icolor2x < 10: "0x0" else: "0x") & &"{icolor2x:x}"

# Convert PGM's 8-bit 256 color code to 4-bit 16 colors (2 pixels/byte)
proc color_code_256to16(byte: string): int =
  result = case byte
    of "0": 0 # "0x00"
    of "15": 1 # "0x11"
    of "30": 2 # "0x22"
    of "45": 3 # "0x33"
    of "60": 4 # "0x44"
    of "75": 5 # "0x55"
    of "90": 6 # "0x66"
    of "105": 7 # "0x77"
    of "120": 8 # "0x88"
    of "135": 9 # "0x99"
    of "150": 10 # "0xAA"
    of "165": 11 # "0xBB"
    of "180": 12 # "0xCC"
    of "195": 13 # "0xDD"
    of "210": 14 # "0xEE"
    of "225": 15 # "0xFF"
    else:
      echo "Invalid color code: {byte}"
      quit QuitFailure


main()
